[general]
import = [
    "alacritty-theme/themes/base16_default_dark.toml",
]

[window]
padding = { x = 3, y = 3 }

[font]
size = 12.75
normal = { family = "Noto Sans Mono" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "nu", args = [] }

