[general]
import = [
    "alacritty-theme/themes/catppuccin_mocha.toml",
]

[window]
padding = { x = 3, y = 3 }

[font]
size = 12
normal = { family = "FiraMono Nerd Font Mono" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
