[general]
import = [
    "alacritty-theme/themes/catppuccin_mocha.toml",
    # "alacritty-theme/themes/catppuccin_latte.toml",
]

[window]
padding = { x = 3, y = 3 }

[font]
size = 12.5

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]
# nushell on Windows
shell = { program = "nu", args = [] }
