theme = "everforest_dark"
# theme = "catppuccin_macchiato"
# theme = "catppuccin_latte"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
